(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ac-js2")
(depends-on "ac-nrepl")
(depends-on "auto-complete")
(depends-on "browse-kill-ring")
(depends-on "cask")
(depends-on "clojure-mode")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "js2-mode")
(depends-on "pallet")
(depends-on "popup")
(depends-on "rainbow-delimiters")
(depends-on "s")
(depends-on "simple-httpd")
(depends-on "skewer-mode")
(depends-on "zenburn-theme")